### PR TITLE
Fix save as markdown

### LINKED ISSUE #1622: BUG: Save Results as Markdown Not Working
**Describe the bug**
Using the download Markdown option in the bottom right corner of the results panel does nothing when selected. Having Dev Tools open while trying this will reveal the following warning: `tabulator_esm.js:5143 Download Error - No such download type found:  md`

**To Reproduce**
1. Connect to a database and make a selection in a Query tab 
2. Click on the download button in the bottom right corner
3. Select Markdown
4. Nothing will happen

**Expected behavior**
A markdown file would be saved with the query results saved as a markdown table in the file.

**Screenshots / Gifs**
image

**Version Information (please complete the following information):**
 - OS: MacOs 13.4.1
 - App Version: 3.9.17
 - Database type and version: 10.1.35-MariaDB

### PR DESCRIPTION
**Pull request by not-night-but**
Fix #1622

The fix merged in #1494 inadvertently broke the save as markdown feature, this PR is fixing that.

### CODE REVIEW

**Review by wmontgomery — APPROVED** [review]

File: apps/studio/src/components/editor/ResultTable.vue [hunk 1]
```diff
@@ -275,7 +275,7 @@
         };
         // Fix Issue #1493 Lost column names in json query download
         // by overriding the tabulator-generated json with ...what cipboard() does, below:
-        formatter = format !== 'json' ? format : (rows, options, setFileContents) => {
+        formatter = format !== 'json' ? formatter : (rows, options, setFileContents) => {
```
Comment (davidkaufman) [inline apps/studio/src/components/editor/ResultTable.vue:278]: Good catch, @not-night-but! thanks :-)
