### PR TITLE
Azure SSO authentication improvement

### LINKED ISSUE #2287: FEAT: UI improvements for Azure SSO authentication workflow
When connecting with SSO the following thing happens:
1. Click connect
2. Beekeeper opens a browser tab for the user to complete SSO
3. During this time, beekeeper polls for 2 minutes waiting for the SSO via the webapp, but doesn't display anything in the app to indicate this.
4. After 2 minutes is up, it shows an error.
5. Once authenticated for a connection, we have credentials, so clicking 'connect' will auto-connect you with that token

Problems:
1. There's no way to know that Beekeeper Studio is waiting for the web SSO session to complete
2. There's no way to clear a saved authentication token / change who you are signed in as (like what if you signed in as the wrong user?)
3. There's no way to cancel the polling and connect to a different database

UI items TODO
1. When you click connect, Beekeeper Studio should open a modal that shows a spinner and says something like 'Waiting for authentication...' It should Poll for AS LONG AS THE MODAL IS OPEN. There should be a **cancel** button that stops polling. This prevents folks from connecting to another database at the same time.
2. When someone has authorized themselves for a specific database, we should show that in the AzureSSO connection area, and allow them to 'sign out' and clear the token cache. We don't know the email, but you can say something like `Authenticated on <date> [sign out]`

Ping me and I can share some user credentials.

### PR DESCRIPTION
**Pull request by azmy60**
fix #2287 

image

image

TODOS
- [x] When you click connect, Beekeeper Studio should open a modal that shows a spinner and says something like 'Waiting for authentication...' It should Poll for AS LONG AS THE MODAL IS OPEN. There should be a cancel button that stops polling. This prevents folks from connecting to another database at the same time.
- [X] When someone has authorized themselves for a specific database, we should show that in the AzureSSO connection area, and allow them to 'sign out' and clear the token cache. We don't know the email, but you can say something like Authenticated on <date> [sign out]

### CODE REVIEW

File: apps/studio/src/components/connection/SqlServerForm.vue [hunk 1]
```diff
@@ -177,6 +195,14 @@
             this.config.azureAuthOptions.azureAuthType = this.authType
           }
         }
+
+        const authId = this.config.azureAuthOptions?.authId || this.config?.authId
+        if (this.authType === AzureAuthType.AccessToken && !_.isNil(authId)) {
+          const cache = await TokenCache.findOne(authId);
```
Comment (rathboma) [inline apps/studio/src/components/connection/SqlServerForm.vue:201]: This will have to be moved to the utility process once we merge this to master

**Review by rathboma — APPROVED** [review]
This looks great! Merge away

**Comment by rathboma** [comment]
@azmy60 please fix the test before merging.

Also -- please make a follow up PR for merging this into master

**Comment by azmy60** [comment]
The sql server always run into `unhealty container` over the past few days on my PRs. It looks like an issue from GitHub, but I'll see what I can find.

File: apps/studio/src/components/connection/SqlServerForm.vue (hunk 1 above)
Comment (azmy60) [reply apps/studio/src/components/connection/SqlServerForm.vue:201]: Will do!
