### PR TITLE
fix mysql binary parsing the wrong columns

### LINKED ISSUE #2640: BUG: Tables wont load due to "Cannot read properties of null" error
**Describe the bug**
Tables that up to recently would load properly, now stay blank with a big error: "Error loading data, see error below". This happens to both development and production databases on several servers. The error "below" is, according to the devtools:

```
data fetch error TypeError: Cannot read properties of null (reading 'byteLength')
    at Object.serialize (opt/Beekeeper Studio/resources/app.asar/dist/utility.js:381338:43)
    at opt/Beekeeper Studio/resources/app.asar/dist/utility.js:379868:31
    at Array.forEach (<anonymous>)
    at MariaDBClient.serializeQueryResult (opt/Beekeeper Studio/resources/app.asar/dist/utility.js:379867:40)
    at MariaDBClient.selectTop (opt/Beekeeper Studio/resources/app.asar/dist/utility.js:381770:29)
    at process.processTicksAndRejections (VM33 task_queues:95:5)
    at async conn/selectTop (opt/Beekeeper Studio/resources/app.asar/dist/utility.js:395717:12)
```

It does not happen on all of my tables, some tables do not show an error, but columns remain NULL even though they are not (see screenshot).

**To Reproduce**
I can't entirely make a reproducible error, but I can reproduce the null errors:

Creating a broken table:
```sql
CREATE TABLE `broken_table` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci
```
Inserting some dummy data:
```
INSERT INTO `broken_second_table` (`id`, `uuid`, `name`) VALUES
(3, 'HIVsRcGKkPFtW', 'lorem'),
(1, 'Qwsogvtv82FCd', 'ipsum'),
(5, 'YnFzw1gLeOb1', 'dolor'),
(2, 'razxDUgYGNAdQ', 'sit'),
(4, 'yhjMzLPhuIDl', 'amet');
```

**Screenshots / Gifs**
**NULL column in broken_table:**
image

**Same data but manually queried:**
image

**Entirely broken table:**
image

**Version Information (please complete the following information):**
 - OS: Ubuntu 24.04
 - App Version 5.0.6
 - Database type and version: [10.6.18-MariaDB-ubu2004 and 10.6.18-MariaDB]

### PR DESCRIPTION
**Pull request by not-night-but**
fix #2640
Tentative fix for properly parsing mysql column types for binary parsing

### CODE REVIEW

File: apps/studio/src/lib/db/clients/mysql.ts [hunk 1]
```diff
@@ -618,7 +618,7 @@ export class MysqlClient extends BasicDatabaseClient<ResultType> {
     );
     const { query, params } = queries;
     const result = await this.driverExecuteSingle(query, { params });
-    const fields = this.parseQueryResultColumns(result);
```
Comment (azmy60) [inline apps/studio/src/lib/db/clients/mysql.ts:621]: We can remove `parseQueryResultColumns` if we're not using it.

**Review by azmy60 — CHANGES_REQUESTED** [review]
LGTM! Just one little cleanup and we're good.

**Review by rathboma — APPROVED** [review]

**Comment by React1-X** [comment]
Hi, I downloaded the latest version off the website (5.0.8) - I'm still getting this issue. I'm not sure if this new build has been published to the website or not. Thanks!
