### PR TITLE
Fix: Syncing table columns after updates

### LINKED ISSUE #1751: BUG: Adding a column to a table, then clicking apply doesn't show the column

### LINKED ISSUE #1752: BUG: If I add a column to a table, but have the table data view open in another tab, that doesn't update to show the new table

### PR DESCRIPTION
**Pull request by azmy60**
closes #1751 
closes #1752

### CODE REVIEW

File: apps/studio/src/components/CoreTabs.vue [hunk 1]
```diff
@@ -593,6 +599,17 @@ export default Vue.extend({
...
     },
+    async alterTable(options: { changes: AlterTableSpec, table: TableOrView, onError?: (e: any) => void, onSuccess?: () => void }) {
+      try {
+        await this.connection.alterTable(options.changes)
+        await this.$store.dispatch('updateTableColumns', options.table)
+        options.onSuccess?.()
+        this.trigger(AppEvent.tableAltered, options.table)
+      } catch (e) {
+        log.error(e);
+        options.onError?.(e)
```
Comment (rathboma) [inline apps/studio/src/components/CoreTabs.vue:610]: It's not a good idea to pass functions around on the event bus. It's really just for data.

I don't really see the reason for `alterTable` to be pushed up to CoreTabs, why can't this stay in `TableSchema`?

File: apps/studio/src/components/tableinfo/TableSchema.vue [hunk 2]
```diff
@@ -366,23 +356,21 @@ export default Vue.extend({
...
-        this.error = null
-        const changes = this.collectChanges()
-        await this.connection.alterTable(changes)
-
-        this.clearChanges()
-        await this.$store.dispatch('updateTableColumns', this.table)
-        this.$nextTick(() => {
+    async submitApply() {
+      this.error = null
+      this.trigger(AppEvent.alterTable, {
```
Comment (rathboma) [inline apps/studio/src/components/tableinfo/TableSchema.vue:361]: Why did you move the alterTable function to CoreTabs? I don't see why it can't stay in here?

We should not be passing functions through the event bus

File: apps/studio/src/components/CoreTabs.vue [hunk 3]
```diff
@@ -593,6 +599,17 @@ export default Vue.extend({
       this.tableExportOptions = options
       this.showExportModal = true
     },
+    async alterTable(options: { changes: AlterTableSpec, table: TableOrView, onError?: (e: any) => void, onSuccess?: () => void }) {
+      try {
+        await this.connection.alterTable(options.changes)
+        await this.$store.dispatch('updateTableColumns', options.table)
```
Comment (rathboma) [inline apps/studio/src/components/CoreTabs.vue:605]: won't updating the table columns just force an update to the TableTable without an extra event? I think there's a watcher on the columns already no?

**Review by rathboma — CHANGES_REQUESTED** [review]
Bunch of questions, but notably -- let's not pass functions on the event bus!

File: apps/studio/src/components/CoreTabs.vue (hunk 3 above)
Comment (azmy60) [reply apps/studio/src/components/CoreTabs.vue:605]: Yeah but for some reason it didn't detect the changes automatically, even after calling the updateColumnsTable

Comment (azmy60) [reply apps/studio/src/components/CoreTabs.vue:605]: Wait, let me find why the watcher didn't work.

**Comment by azmy60** [comment]
Ok, fixed the root cause!

**Review by rathboma — APPROVED** [review]
