### PR TITLE
Fix invalid sql array format on copy

### LINKED ISSUE #1596: BUG: Invalid SQL for "Copy insert" action of dropdown in table for Postgres
**Describe the bug**
Invalid SQL for "Copy Insert" action of dropdown in table data with array column for Postgres.

**To Reproduce**
1. Create table with array column and insert row.
2. Open table.
3. Click RMB on table row then click "Copy Row (insert)"
4. Paste and run copied query.

**Expected behavior**
The insertion was successful.

**Version Information (please complete the following information):**
 - OS: macOS Ventura 13.3.1
 - App Version: 3.9.9
 - Database: Postgres 10.4

**Additional context**
Expected SQL, ex.:
```sql
insert into "public"."test" ("some_array") values ('{1,9,2,10,11}');
```
Actual SQL with error, ex.:
```sql
insert into "public"."test" ("some_array") values ('[1,9,2,10,11]');
```

### PR DESCRIPTION
**Pull request by azmy60**
Instead of mutating the array/object into string for the whole table, we can convert them into string when viewing and editing, so we don't lose the real data type when calling `tabulator.getData()`. Preserving the real data type so knex can generate the query for us correctly.

Animation4

Changes:

- copy to SQL.
before => `insert into "public"."untitled_table" ("column_3") values ('[1,2,3,4,5]')`
after => `insert into "public"."untitled_table" ("column_3") values ('{1,2,3,4,5}')`

- copy to JSON
before => `["column_1":"[1,2,3]"}]`
after => `["column_1":[1,2,3]}]`

- copy to TSV for excel
before => `"1"	"2023-09-21 01:57:29.227987"	"[1,2,3]"`
after => `"1"	"2023-09-21 01:57:29.227987"	"1,2,3"`

- copy to Markdown
before => 
```md
| id | created_at                 | column_3 |
| -- | -------------------------- | -------- |
| 1  | 2023-09-21 01:57:29.227987 | [1,2,3]  |
```

after => 
```md
| id | created_at                 | column_3 |
| -- | -------------------------- | -------- |
| 1  | 2023-09-21 01:57:29.227987 | 1,2,3    |
```

Closes #1596

todo:
- [x] check result table
- [x] exporting sql using the exporter window is still wrong
- [x] check mysql json
- [x] bigquery array

### CODE REVIEW

**Comment by azmy60** [comment]
@rathboma This PR would remove all the JSON centric array and objects format. So in md, tsv, etc.. we no longer stick with the json array brackets.

If we would do this change of copy styles, we will need to update the exporter too. Or just do this to the sql copy, it's up to you.

File: apps/studio/src/components/tableview/TableTable.vue [hunk 1]
```diff
@@ -640,6 +640,11 @@ export default Vue.extend({
               ? [true, false]
               : undefined,
             allowEmpty: true,
+            preserveObject: column.dataType.startsWith('_'),
```
Comment (rathboma) [inline apps/studio/src/components/tableview/TableTable.vue:643]: This looks like a good solution!

This will only fix this for Postgres though, correct? How do other database types identify arrays?

**Review by rathboma — CHANGES_REQUESTED** [review]
This looks perfect. One question: How are arrays identified in other dialects?

File: apps/studio/src/components/tableview/TableTable.vue (hunk 1 above)
Comment (rathboma) [reply apps/studio/src/components/tableview/TableTable.vue:643]: Isn't the value an array to begin with? If so, can't it preserve object by default for all arrays?

Comment (azmy60) [reply apps/studio/src/components/tableview/TableTable.vue:643]: Yup! Since postgres is the only database that support arrays, so this is safe IMO. However, mysql support json. So I'm gonna need to look at that to finish up the PR.

Comment (not-night-but) [reply apps/studio/src/components/tableview/TableTable.vue:643]: @azmy60 I don't know about other databases, but BigQuery does support arrays so maybe test that

Comment (rathboma) [reply apps/studio/src/components/tableview/TableTable.vue:643]: @azmy60 Hmm, if the mutator is converting from an array, that's probably not correct. I think we have a `preserveComplex` flag that is supposed to help fix that?

Good catch on the nullable editor turning the value into a string -- that definitely needs fixing. If the value is an array, or a json object, it should just keep it that way.

For background, Tabulator has 2 ways to manipulate values:
- Mutators - changes the ACTUAL value when set
- Formatters - only changes how the values are DISPLAYED

So mutators should def keep them as complex types when appropriate. See `genericMutator`. This has a `preserveComplex` argument that can be set to true. See also `resolveDataMutator`

`niceString` is only used in a formatter, so don't worry about that one.

Comment (rathboma) [reply apps/studio/src/components/tableview/TableTable.vue:643]: Sorry, this ended up way more complex than I thought it would be :-D

Comment (azmy60) [reply apps/studio/src/components/tableview/TableTable.vue:643]: Sorry, the `preserveObject` flag is a parameter for the nullable editor. It's the fix for turning the value back into it's original type when changing some values from cells.

As of `preserveComplex` in `genericMutator`, I had switched that to [true](https://github.com/beekeeper-studio/beekeeper-studio/pull/1708/files#diff-c43a89ad7180e5dcda2d74247d1a2823e3399ffd622b3fd5eee1af3b3ebd7b87L12-R15).

**Comment by azmy60** [comment]
@not-night-but I still can't connect to bigquery for some reason. It tries to connect to an invalid url 🤔 ?

image

File: apps/studio/src/components/tableview/TableTable.vue (hunk 1 above)
Comment (wmontgomery) [reply apps/studio/src/components/tableview/TableTable.vue:643]: This all look super helpful for an issue we're seeing with import where arrays are causing DB insert errors.

File: apps/studio/src/components/tableview/TableTable.vue [hunk 2]
```diff
@@ -647,6 +647,11 @@ export default Vue.extend({
             verticalNavigation: useVerticalNavigation ? 'editor' : undefined,
             search: true,
             allowEmpty: true,
+            preserveObject: column.dataType.startsWith('_'),
+            onPreserveObjectFail: () => {
```
Comment (rathboma) [inline apps/studio/src/components/tableview/TableTable.vue:651]: Probably this should just log to the console or something?

If there are 500 rows, this will trigger 500 times

**Review by rathboma — CHANGES_REQUESTED** [review]
One final thing -- not spamming the user with `$noty` error messages :-D. Then good to go

File: apps/studio/src/components/tableview/TableTable.vue (hunk 2 above)
Comment (azmy60) [reply apps/studio/src/components/tableview/TableTable.vue:651]: Oh yeah, that's really bad 😆

**Review by rathboma — APPROVED** [review]
