### PR TITLE
Fix #2489: Cannot select / copy relation names in UI

### LINKED ISSUE #2489: BUG: Cannot select / copy relation names in UI
**Describe the bug**
In the table structure page > relations, we cannot select and copy relation names.

**To Reproduce**
1. Go to table structure (right click on table, "View Structure").
2. Go to "Relations" tab.
3. Cannot copy / select anything in the relations table.

**Expected behavior**
Should be able to select / copy anything from relations table.

**Screenshots / Gifs**

https://github.com/user-attachments/assets/0a16b605-4ca1-4fda-9282-595750c1a37b

**Version Information (please complete the following information):**
 - OS: macOS 15.1 Public Beta 3
 - App Version: 4.6.8
 - Database type and version: Postgres 15

### PR DESCRIPTION
**Pull request by RodrigoPerestrelo**
In the table structure page > Indexes, Relations and Triggers, we cannot select the relation name to copy it.
I created a method (handleCellDoubleClick(cell)) in the Vue files TableRelations, TableIndexes, and TableTriggers to handle double-click selection. I added this method to the respective columns (only those that made sense to me, avoiding fields such as checkboxes).
Close #2489

### CODE REVIEW

File: apps/studio/src/components/tableinfo/TableTriggers.vue [hunk 1]
```diff
@@ -88,6 +88,32 @@ export default {
...
+      // Function to remove contenteditable when clicking anywhere
+      const removeEditable = (event) => {
+        element.removeAttribute("contenteditable");
+        document.removeEventListener("click", removeEditable);
+      };
+
+      // Attach a global event listener
+      document.addEventListener("click", removeEditable);
+    }
+  },
```
Comment (not-night-but) [inline apps/studio/src/components/tableinfo/TableTriggers.vue:116]: Since this same function is used in all three components, I'd prefer if we add it to a mixin (you can probably create a mixin specifically for this as I don't think it really fits with any of our others). That way we don't have code duplication, and we can add this functionality easily to any other tables that exist in the future. Let me know if you have any questions about how mixins work, but you can look at our fk_click.ts mixin for an example.

**Review by not-night-but — CHANGES_REQUESTED** [review]
Good job! This functions well, I just think we need to not have as much code duplication, so we should probably add a mixin for the `handleCellDoubleClick` function.

**Review by not-night-but — APPROVED** [review]
