### PR TITLE
Bugfix/1477 create table

### LINKED ISSUE #1477: BUG: new update broke the 'create table' function
**Describe the bug**
new update broke the 'create table' function

**To Reproduce**
1. Go to a DB
2. Click on the + icon to create a new table
3. See error --> page is blank

**Expected behavior**
should have a table creation gui

**Screenshots / Gifs**
Screen_Shot_2023-01-13_at_16_35_10

**Version Information (please complete the following information):**
 - OS: [e.g. Windows/Mac/Ubuntu]
 - App Version [e.g. help -> About Beekeeper Studio]
 - Database type and version [eg Posgresql 9.3]

**Additional context**
Anything else you think might be helpful

### PR DESCRIPTION
**Pull request by wmontgomery**
fix #1477 

Issue was mysql and sqlite were missing the defaultSchema functions, so those were added to each client/*dialect*.js file as an empty string.

Also fixed a style issue when closing a table-builder tab.

### CODE REVIEW

**Review by rathboma — APPROVED** [review]

**Comment by rathboma** [comment]
@wmontgomery does that need adding to Oracle and Cassandra in the ultimate edition?

**Comment by wmontgomery** [comment]
@rathboma There is a defaultSchema function in the oracle client, and I'll be sure to make note of it for the Cassandra side when I'm working through Write. Chances are it will need to be since most of the client pieces were taken from MySQL's.

File: apps/studio/src/lib/db/clients/sqlite.js [hunk 1]
```diff
@@ -38,6 +38,7 @@ export default async function (server, database) {
     supportedFeatures: () => ({ customRoutines: false, comments: false, properties: true }),
     versionString: () => getVersionString(version),
     wrapIdentifier,
+    defaultSchema: () => '',
```
Comment (rathboma) [inline apps/studio/src/lib/db/clients/sqlite.js:41]: @wmontgomery i think if there is no schema this should return null, no?  Aren’t we going to want to do checks like if(schema).

Comment (rathboma) [reply apps/studio/src/lib/db/clients/sqlite.js:41]: This is how we handle no schema elsewhere in the code. Can we make this change and check table creation still works?

Comment (rathboma) [reply apps/studio/src/lib/db/clients/sqlite.js:41]: I'm changing it to return null
